### ISSUE TITLE
Installation issue with GIMP

### ISSUE THREAD

**Issue by c-pupil** [niladridutt/monetGPT#7]
Hello,
First of all, thank you for this excellent work! When trying to run the project on a remote server, I encountered an installation problem for the specified GIMP version:
`error: Nothing matches org.gimp.GIMP in remote flathub`

I would like to ask:

- Will the project completely remove the GIMP dependency in the future and fully migrate the relevant operations to Python? If so, could you share an approximate timeline for this migration?

- Does this change mean that will need to regenerate the puzzle data and retrain the model from scratch?

Thank you very much for your time and effort!

**Comment by niladridutt** [comment]
Hi @c-pupil 

Thanks for the kind words!

I've updated the readme for a more detailed guide to install GIMP.

The below command should fix the issue.

`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

1. Removing GIMP dependency will need some time and I'm currently unsure when it will happen .. could take anywhere from a few weeks to maybe a few months depending when I'm free from other projects. 
2.  I will try to align the operations to match the GIMP ones. If my implementation does not follow GIMP closely, then yes I'm afraid so.

**Comment by c-pupil** [comment]
@niladridutt  Thank you for your previous suggestion. I have tried adding the Flathub repository as follows:
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` 
However, the problem still persists when I attempt to install GIMP.

**Comment by Ethereal-sakura** [comment]
Hello, I'm having the same issue. Did you manage to resolve it in the end?
